version: "3.7"

networks:
  analytics-net:
    external: true

services:
  coordinator:
    image: trinodb/trino
    ports:
      - "8080:8080"
    container_name: coordinator
    networks:
      - analytics-net
    volumes:
      - ./coordinator/etc/trino:/etc/trino
  worker0:
    image: trinodb/trino
    container_name: worker0
    ports:
      - "8081:8081"
    networks:
      - analytics-net
    volumes:
      - ./node1/etc/trino:/etc/trino
  worker1:
    image: trinodb/trino
    container_name: worker1
    ports:
      - "8082:8081"
    networks:
      - analytics-net
    volumes:
      - ./node2/etc/trino:/etc/trino