version: "3"


networks:
  analytics-net:
    external: true

services:
  zeppelin:
    image: apache/zeppelin:0.9.0
    networks:
      - analytics-net
    volumes:
      - ./spark-source/spark-3.0.0-bin-hadoop3.2:/spark
    ports:
      - "10088:8080"
    restart: always
